version: "3.9"
services:
  application:
    build:
      context: ../
      dockerfile: billMan/Dockerfile
    environment:
      - environment
      - domain
      - audience
      - realm
      - secret
      - keystore
      - keyAlias
      - keyStorePassword
      - privateKeyPassword