rootProject.name = "weesnerDevelopment"
include("auth")
include("backend")
include("businessRules")
include("taxFetcher")
include("billMan")
include("generator")
include("breathOfTheWild")
include("serialCabinet")
include("testUtils")
