version: "3.9"
services:
  application:
    build:
      context: ../
      dockerfile: auth/Dockerfile
    ports:
      - "8081:8081"
      - "8444:8444"
    environment:
      - environment
      - domain
      - audience
      - realm
      - secret
      - keystore
      - keyAlias
      - keyStorePassword
      - privateKeyPassword