name: Build, test and publish Auth service

on:
  push:
  #    branches:
  #      - main
#    paths:
#      - auth/**

jobs:
  auth-service:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: latest

      - name: Build and push
        id: build
        uses: docker/build-push-action@v3
        with:
          file: ./auth/Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}

      - name: Echo outputs
        run: echo "${{ toJSON(steps.build.outputs) }}"

    #      - uses: actions/checkout@v2

    #      - name: Set up JDK
    #        uses: actions/setup-java@v3
    #        with:
    #          java-version: '11'
    #          distribution: 'adopt'
    #
    #      - name: Validate Gradle wrapper
    #        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    #
    #      - name: Build and Test
    #        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
    #        with:
    #          arguments: :auth:build

    #      - name: Publish
    #        id: publish
    #        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
    #        env:
    #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #        with:
    #          arguments: :auth:publish

    #      - name: Echo outputs
    #        run: echo "${{ toJSON(steps.publish.outputs) }}"
