name: BillMan service

env:
  pathToWatch: billMan/**
  buildPath: :billMan:build
  dockerTag: billMan:latest
  dockerfilePath: ./billMan/Dockerfile

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - env.pathToWatch

jobs:
  billman-service:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build and Test
        id: bat
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: ${{ env.buildPath }}

      - name: Set up Docker Buildx
        if: ${{ steps.bat.outcome == 'success' }}
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: ${{ steps.bat.outcome == 'success' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        if: ${{ steps.bat.outcome == 'success' }}
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: ${{ env.dockerTag }}

      - name: Build and push
        if: ${{ steps.bat.outcome == 'success' }}
        id: build
        uses: docker/build-push-action@v3
        with:
          file: ${{ env.dockerfilePath }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
